---
- hosts: localhost
  tasks:
      - debug: msg="{{build_dir}}"
      - file: path={{ build_dir }}/build state=directory mode=0755
      - file: path={{ build_dir }}/src state=directory mode=0755
      - file: path={{ build_dir }}/src/webui state=directory mode=0755
      - file: path={{ build_dir }}/release state=directory mode=0755
      - git: repo={{ repo }}/gohan dest="{{ build_dir}}/src/gohan"
      - get_url: url={{ gohan_webui_download_path }} dest="{{ build_dir }}/src/"
      - unarchive: src="{{ build_dir }}/src/gohan_webui.zip" dest="{{ build_dir }}/src/webui/"
      - copy: src="{{ build_dir }}/src/webui/config.json.sample" dest="{{ build_dir }}/src/webui/config.json"
      - file: path={{ build_dir }}/build/{{ item }} state=directory mode=0755
        with_items: "{{ supported_arch }}"
      - get_url: url="{{ gohan_download_site }}/gohan-{{ item }}.zip" dest="{{ build_dir }}/build/{{ item }}/gohan.zip"
        with_items: "{{ supported_arch }}"
      - unarchive: src="{{ build_dir }}/build/{{ item }}/gohan.zip" dest="{{ build_dir }}/build/{{ item }}/"
        with_items: "{{ supported_arch }}"
      - file: path="{{ build_dir }}/build/{{ item }}/gohan.zip" state=absent
        with_items: "{{ supported_arch }}"
      - synchronize: src="{{ build_dir }}/src/gohan/etc" dest="{{ build_dir }}/build/{{ item }}/"
        with_items: "{{ supported_arch }}"
      - synchronize: src="{{ build_dir }}/src/webui" dest="{{ build_dir }}/build/{{ item }}/etc/"
        with_items: "{{ supported_arch }}"
      - command: "zip -r {{ build_dir }}/release/gohan_{{ item }}.zip . "
        args:
           chdir: "{{ build_dir }}/build/{{ item }}"
        with_items: "{{ supported_arch }}"
